# ==========================
# ZOOKEEPER HEADLESS SERVICE
# ==========================
apiVersion: v1
kind: Service
metadata:
  name: zookeeper-hs
spec:
  ports:
  - name: client
    port: 2181
    targetPort: 2181
  clusterIP: None  # Headless service
  selector:
    app: zookeeper
---
# ==========================
# ZOOKEEPER SERVICE (for client access)
# ==========================
apiVersion: v1
kind: Service
metadata:
  name: zookeeper-service
spec:
  ports:
  - name: client
    port: 2181
    targetPort: 2181
  selector:
    app: zookeeper
---
# ==========================
# ZOOKEEPER STATEFULSET
# ==========================
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: zookeeper
spec:
  serviceName: "zookeeper-hs"
  replicas: 1
  selector:
    matchLabels:
      app: zookeeper
  template:
    metadata:
      labels:
        app: zookeeper
    spec:
      containers:
      - name: zookeeper
        image: confluentinc/cp-zookeeper:7.5.0
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 2181
          name: client
        env:
        - name: ZOOKEEPER_CLIENT_PORT
          value: "2181"
        - name: ZOOKEEPER_TICK_TIME
          value: "2000"
        - name: ZOOKEEPER_SERVER_ID
          value: "1"
        volumeMounts:
        - name: zookeeper-data
          mountPath: /var/lib/zookeeper/data
  volumeClaimTemplates:
  - metadata:
      name: zookeeper-data
    spec:
      accessModes: [ "ReadWriteOnce" ]
      resources:
        requests:
          storage: 1Gi
---
# ==========================
# KAFKA HEADLESS SERVICE
# ==========================
apiVersion: v1
kind: Service
metadata:
  name: kafka-hs
spec:
  ports:
  - name: broker
    port: 9092
    targetPort: 9092
  clusterIP: None  # Headless service
  selector:
    app: kafka
---
# ==========================
# KAFKA SERVICE (for client access)
# ==========================
apiVersion: v1
kind: Service
metadata:
  name: kafka-service
spec:
  ports:
  - name: broker
    port: 9092
    targetPort: 9092
  selector:
    app: kafka
---
# ==========================
# KAFKA STATEFULSET
# ==========================
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: kafka
spec:
  serviceName: "kafka-hs"
  replicas: 1
  selector:
    matchLabels:
      app: kafka
  template:
    metadata:
      labels:
        app: kafka
    spec:
      containers:
      - name: kafka
        image: confluentinc/cp-kafka:7.5.0
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 9092
          name: broker
        env:
        - name: KAFKA_BROKER_ID
          value: "1"
        - name: KAFKA_ZOOKEEPER_CONNECT
          value: "zookeeper-service:2181"
        - name: KAFKA_LISTENERS
          value: "PLAINTEXT://0.0.0.0:9092"
        - name: KAFKA_ADVERTISED_LISTENERS
          value: "PLAINTEXT://kafka-0.kafka-hs.default.svc.cluster.local:9092"
        - name: KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR
          value: "1"
        - name: KAFKA_TRANSACTION_STATE_LOG_MIN_ISR
          value: "1"
        - name: KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR
          value: "1"
        volumeMounts:
        - name: kafka-data
          mountPath: /var/lib/kafka/data
  volumeClaimTemplates:
  - metadata:
      name: kafka-data
    spec:
      accessModes: [ "ReadWriteOnce" ]
      resources:
        requests:
          storage: 2Gi